---
site_name: terraform-google-gke

repo_name: padok-team/terraform-google-gke
repo_url: https://github.com/padok-team/terraform-google-gke

plugins:
  - techdocs-core
  - include-markdown

nav:
  - Reference: index.md
  - Usage:
    - Standard: 'usage/standard.md'
    - Private:  'usage/private.md'
    - Options:  'usage/options.md'
